package com.testdataobject.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class emp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("test")
	private java.util.List<com.testdataobject.test.Evaluation> test;

	@org.kie.api.definition.type.Label("fname")
	private java.lang.String fname;

	@org.kie.api.definition.type.Label("lname")
	private java.lang.String lname;

	@org.kie.api.definition.type.Label("address")
	private java.lang.String address;

	@org.kie.api.definition.type.Label("location")
	private java.lang.String location;

	@org.kie.api.definition.type.Label("radio_group_selector")
	private java.lang.String radio_group_selector;

	@org.kie.api.definition.type.Label("list_box_selector")
	private java.lang.String list_box_selector;

	@org.kie.api.definition.type.Label(value = "list_box")
	private java.lang.String list_box;

	public emp() {
	}

	public java.util.List<com.testdataobject.test.Evaluation> getTest() {
		return this.test;
	}

	public void setTest(java.util.List<com.testdataobject.test.Evaluation> test) {
		this.test = test;
	}

	public java.lang.String getFname() {
		return this.fname;
	}

	public void setFname(java.lang.String fname) {
		this.fname = fname;
	}

	public java.lang.String getLname() {
		return this.lname;
	}

	public void setLname(java.lang.String lname) {
		this.lname = lname;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getLocation() {
		return this.location;
	}

	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getRadio_group_selector() {
		return this.radio_group_selector;
	}

	public void setRadio_group_selector(java.lang.String radio_group_selector) {
		this.radio_group_selector = radio_group_selector;
	}

	public java.lang.String getList_box_selector() {
		return this.list_box_selector;
	}

	public void setList_box_selector(java.lang.String list_box_selector) {
		this.list_box_selector = list_box_selector;
	}

	public java.lang.String getList_box() {
		return this.list_box;
	}

	public void setList_box(java.lang.String list_box) {
		this.list_box = list_box;
	}

	public emp(java.util.List<com.testdataobject.test.Evaluation> test,
			java.lang.String fname, java.lang.String lname,
			java.lang.String address, java.lang.String location,
			java.lang.String radio_group_selector,
			java.lang.String list_box_selector, java.lang.String list_box) {
		this.test = test;
		this.fname = fname;
		this.lname = lname;
		this.address = address;
		this.location = location;
		this.radio_group_selector = radio_group_selector;
		this.list_box_selector = list_box_selector;
		this.list_box = list_box;
	}

}